# Generated by Django 3.0.3 on 2020-09-08 12:11

from django.db import migrations, models
import django.db.models.functions.datetime


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niceTitle', models.CharField(max_length=120)),
                ('niceContent', models.CharField(max_length=200)),
                ('niceAuthor', models.CharField(max_length=100)),
                ('niceDate', models.DateTimeField(verbose_name=django.db.models.functions.datetime.Now)),
            ],
        ),
    ]
