# Generated by Django 3.0.3 on 2020-09-08 12:18

from django.db import migrations, models
import django.db.models.functions.datetime


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nice',
            name='niceDate',
            field=models.DateTimeField(blank=True, verbose_name=django.db.models.functions.datetime.Now),
        ),
    ]
