# Generated by Django 3.0.3 on 2020-09-08 12:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20200908_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nice',
            name='niceDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
