# Generated by Django 3.0.3 on 2020-09-12 07:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20200908_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nice',
            name='niceDate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
