# Generated by Django 3.0.3 on 2020-09-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_auto_20200912_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Figure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('figTitle', models.CharField(max_length=10)),
                ('figImage', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
