# Generated by Django 3.0.3 on 2020-09-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_figure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteTitle', models.CharField(max_length=100)),
                ('noteContent', models.CharField(max_length=300)),
            ],
        ),
    ]
